name: Industry level DevSecOps CICD Pipeline

on:
  push:
    branches:
      - qa
    paths:
      - client/**
      - server/**
      - .github/workflows/qa-cicd.yml
      - sonar-project.properties # this is only for temp time of period

jobs:
  gitleaks-scan:
    name: GitLeak Scan
    runs-on:  ubuntu-latest
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v4

      - name: Run Git Leaks Scan
        run: |
          docker run --rm \
          -v "${{ github.workspace }}:/repo" \
          zricethezav/gitleaks:latest detect \
          --source=/repo \
          --report-format=json \
          --report-path=/repo/gitleaks-report.json \
          --redact \
          --exit-code 0

      - name: upload Git Leaks report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
          if-no-files-found: warn

  checkov-terraform:
    name: Checkov Teraaform Scan
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Chekout Source Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Checkov
        run: |
          checkov -d . \
          --framework terraform \
          --output json > checkov-terraform-report.json || true
      - name: Upload Checkov Terraform Report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-terraform-report
          path: checkov-terraform-report.json
          if-no-files-found: warn

  checkov-dockerfile:
    name: Checkov Dockerfile Scan
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Checkov
        run: |
          checkov -d . \
          --framework dockerfile \
          --output json > checkov-dockerfile-report.json || true
      - name: Upload Checkov Dockerfile Report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-dockerfile-report
          path: checkov-dockerfile-report.json
          if-no-files-found: warn

  checkov-k8s:
    name: Checkov K8s Scan
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: checkout Source Code
        uses: actions/checkout@v4
      - name: setup python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Checkov
        run: |
          checkov -d . \
          --framework kubernetes \
          --output json > checkov-kubernetes-report || true
      - name: Upload Checkov kubernetes Report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-kubernetes-report
          path: checkov-kubernetes-report.json
          if-no-files-found: warn

  client-trivy-fs:
    name: Client Trivy FS Scan
    runs-on: ubuntu-latest
    needs: gitleaks-scan


    steps:
      - name: Chekout Source Code
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.6
        with:
          version: "latest"
          cache: true
      - name: Verify Trivy Installation
        run: |
          trivy --version
          which trivy

      - name: Run Trivy FS Scan on client (json)
        run: |
          trivy fs ./client \
          --format json \
          --output client-trivy-fs-report.json \
          --severity HIGH,CRITICAL \
          --ignore-unfixed \
          --exit-code 0

      - name: Run Trivy FS Scan on Client (Table)
        run: |
          trivy fs ./client \
          --format table \
          --severity HIGH,CRITICAL \
          --ignore-unfixed \
          --exit-code 0 > client-trivy-fs-report.txt

      - name: Upload Trivy Json report
        uses: actions/upload-artifact@v4
        with:
          path: client-trivy-fs-report.json
          if-no-files-found: warn

      - name: Upload the Trivy Table report
        uses: actions/upload-artifact@v4
        with:
          path: client-trivy-fs-report-table.txt
          if-no-files-found: warn

  server-trivy-fs:
    name: Server Trivy FS Scan
    runs-on: ubuntu-latest
    needs: gitleaks-scan

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.6
        with:
          version: "latest"
          cache: true

      - name: Verify the Installation
        run: |
            trivy --version
            which trivy

      - name: Run Trivy Scan on Server (json)
        run: |
            trivy fs ./server \
            --format json \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 0 > server-trivy-fs-report.json

      - name: Run Trivy Scan on server (Table)
        run: |
            trivy fs ./server \
            --format table \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 0 > server-trivy-fs-report-table.txt

      - name: Upload the Artifacts of Server (Json)
        uses: actions/upload-artifact@v4
        with:
          path: server-trivy-fs-report.json
          if-no-files-found: warn

      - name: Upload the Artifact of Server (Table)
        uses: actions/upload-artifact@v4
        with:
          path: server-trivy-fs-report.txt
          if-no-files-found: warn

  client-lint:
    name: Client lint
    runs-on: ubuntu-latest
    needs:
      - client-trivy-fs
      - checkov-k8s
      - checkov-dockerfile
      - checkov-terraform

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout Scource Code
        uses: actions/checkout@v4

      - name: Setup Node js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install Client Dependencies
        run: npm ci

      - name: Run Client lint
        run: npm run lint --if-present
        continue-on-error: true

  server-lint:
    name: server lint
    runs-on: ubuntu-latest
    needs:
      - server-trivy-fs
      - checkov-k8s
      - checkov-dockerfile
      - checkov-terraform

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: server/package-lock.json

      - name: Install Server Dependencies
        run: npm ci

      - name: Run Server Lint
        run: npm run lint --if-present
        continue-on-error: true

  client-test:
    name: client test
    runs-on: ubuntu-latest

    needs: client-lint

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Stepup Node js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install client Dependencies
        run: npm ci

      - name: Run Client test
        run: npm run test --if-present
        continue-on-error: true

  server-test:
    name: Server test
    runs-on: ubuntu-latest

    needs: server-lint

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Step Node Js
        uses: actions/setup-node@v4
        with:
         node-version: 18
         cache: npm
         cache-dependency-path: server/package-lock.json

      - name: Install Server Dependencies
        run: npm ci

      - name: Run Server test
        run: npm run test --if-present
        continue-on-error: true

  sonarube:
    name: Sonar Qube Analysis & Quality Gate Check
    runs-on: ubuntu-latest
    needs:
     -  client-test
     -  server-test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL}}

      - name: sonarQube Quality Gate Status
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL}}
      - name: "Example shoe sonar Qube Quality Gate Status Value"
        run: echo "The Quality Gate Status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status}}"

  client-build:
    name: Client Build
    runs-on: ubuntu-latest
    needs: client-test

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node Js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install client Dependencies
        run: npm ci

      - name: Build the Client
        run: npm run build --if-present
        continue-on-error: true
